SET search_path TO ba_site;

DROP TABLE IF EXISTS funnel_history CASCADE;
DROP TABLE IF EXISTS lead_funnel_positions CASCADE;
DROP TABLE IF EXISTS funnel_stages CASCADE;
DROP TABLE IF EXISTS funnels CASCADE;
DROP TABLE IF EXISTS lead_interactions CASCADE;
DROP TABLE IF EXISTS lead_profiles CASCADE;
DROP TABLE IF EXISTS lead_aliases CASCADE;
DROP TABLE IF EXISTS lead_consents CASCADE;
DROP TABLE IF EXISTS leads CASCADE;
DROP TABLE IF EXISTS scoring_rules CASCADE;
DROP TABLE IF EXISTS user_roles CASCADE;
